[providers]
nodejs = {}

[variables]
NODE_VERSION = "20.19.0"
NODE_ENV = "production"
PORT = "3000"

[build]
cmds = [
    "npm run railway:build"
]

[start]
cmd = "npm run railway:start"

[phases.build]
cmds = [
    "echo 'Building Pet Tracker for Railway...'",
    "cd frontend && npm ci",
    "cd frontend && npm run build:prod", 
    "echo 'Build completed successfully!'"
]
